eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15

hd:
  url: http://10.130.12.22:7280/cre-agency-server
  media:
    url: http://10.130.12.22:8280/HDMediaService-Web

sync:
  cron:
    modality: 0 0 0 * * ?
    brand: 0 0 0 * * ?
    baseinfo: 0 0 0 * * ?
    shop: 0 10 0 * * ?
    merchant: 0 0 0 * * ?