spring:
  datasource:
    url: jdbc:mysql://10.130.12.15:3306/online_leasing_db_dev?characterEncoding=utf8&useSSL=false
    username: oldev%oldev
    password: p@ssw0rd
  redis:
    host: 10.130.12.15
    password: Sbm123

eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/

hd:
  url: http://10.130.12.22:7280/cre-agency-server
  media:
    url: http://10.130.12.22:8280/HDMediaService-Web

sync:
  cron:
    modality: 0 0 0 * * ?
    brand: 0 0 0 * * ?
    baseinfo: 0 0 0 * * ?
    shop: 0 10 0 * * ?