spring:
  application:
    name: sync-hd
  profiles:
    include: common, data, redis
    active: dev, db_ol_dev, redis_dev, eureka_dev

server:
  port: 8773
  context-path:

init:
  shop:
    vr:
      path: upload/vr/{0}/{1}/tour.html

