server:
  port: 8771
logging:
  file: /home/mircoservice/log/${spring.application.name}.log
eureka:
  instance:
    #ip-address: 10.130.12.15
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: mail
  mail:
    host: smtp.qq.com
    port: 587
    username: 295322187@qq.com
    password: udasczmwhqtabjga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true