server:
  port: 8771
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: mail
  mail:
    host: smtp.qq.com
    port: 587
    username: 295322187@qq.com
    password: udasczmwhqtabjga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true