spring:
  datasource:
    url: jdbc:mysql://10.130.12.15:3306/micro_service
    username: micro_user
    password: microService2018
  mail:
    host: smtp.qq.com
    port: 587
    username: 295322187@qq.com
    password: udasczmwhqtabjga
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
