spring:
  application:
    name: zuul
  profiles:
    include: common
    active: test

server:
  port: 8750
  context-path: /api

zuul:
  routes:
    template:
      path: /template/**
      serviceId: template

