spring:
  application:
    name: zuul
  profiles:
    include: common
    active: test

server:
  port: 8750
  context-path:

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    sync-hd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    onlineleasing-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000