spring:
  application:
    name: zuul
  profiles:
    include: common
    active: test

server:
  port: 8750
  context-path:

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000