spring:
  application:
    name: zuul
  profiles:
    include: common
    active: test

server:
  port: 8750
  context-path:

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

hystrix:
  command:
    sync-hd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000 #10 * 60 * 1000 ms 10分钟
    onlineleasing-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000 #10 * 60 * 1000 ms 10分钟