spring:
  application:
    name: zuul
  profiles:
    include: common
    active: test

server:
  port: 8750
  context-path:

zuul:
  routes:
    template:
      path: /template/**
      serviceId: template
    mail:
      path: /mail/**
      serviceId: mail
