spring:
  application:
    name: zuul
  profiles:
    include: common
    active: dev, eureka_dev

zuul:
  sensitiveHeaders: # 不过滤头部
  host:
    socket-timeout-millis: 600000
    connect-timeout-millis: 600000

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

hystrix:
  command:
    sync-hd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000 #10 * 60 * 1000 ms 10分钟
    onlineleasing-file:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000 #10 * 60 * 1000 ms 10分钟