spring:
  application:
    name: common-message
  profiles:
    include: common, data, redis
    active: dev, eureka_dev, db_ms_dev, redis_dev, mail_exchange, sms_hl95

server:
  port: 8700
  context-path:
