spring:
  datasource:
    url: jdbc:mysql://10.130.12.15:3306/micro_service?characterEncoding=utf8&useSSL=false
    username: micro_user
    password: microService2018
  redis:
    host: 10.130.12.15
    password: Sbm123
  mail:
    host: exchange.superbrandmall.com
    port: 25
    username: onlineleasing@superbrandmall.com
    password: '@abc1234'
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/

sms:
  hl95:
    username: dtfz
    password: Dtfz1697
    epid: 123107
