spring:
  datasource:
    url: jdbc:oracle:thin:@10.130.8.88:1521:BIDW
    username: ol
    password: ol
  redis:
    host: 10.130.12.15
    password: Sbm123

eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
