eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1

verify:
  mailTemplateCode: CMAILTEMP170801000001
  smsTemplateCode: CMAILTEMP170801000002

reservation:
  leasing:
    mail:
      templateCode: CMAILTEMP170801000004
      name: 租赁测试员
      email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com,christina.cheng@superbrandmall.com
  event:
    mail:
      templateCode: CMAILTEMP170801000004
      name: 场地测试员
      email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com,christina.cheng@superbrandmall.com
  customer:
    sms:
      templateCode: CMAILTEMP170801000003