eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15

verify:
  mailTemplateCode: CMAILTEMP170801000001
  smsTemplateCode: CMAILTEMP170801000002

reservation:
  leasing:
    mail:
      templateCode: CMAILTEMP170801000004
      leasingName: 租赁测试员
      leasingMail: junkai.zhang@superbrandmall.com
  customer:
    sms:
      templateCode: CMAILTEMP170801000003