eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15

verify:
  mailTemplateCode: CMAILTEMP170801000001
  smsTemplateCode: CMAILTEMP170801000002

reservation:
  leasing:
    mail:
      leasing:
        templateCode: CMAILTEMP170801000004
        name: 租赁测试员
        email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com
      event:
        templateCode: CMAILTEMP170801000004
        name: 场地测试员
        email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com
  customer:
    sms:
      templateCode: CMAILTEMP170801000003