eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1

verify:
  mailTemplateCode: CMAILTEMP170801000001
  smsTemplateCode: CMAILTEMP170801000002

reservation:
  emp:
    leasing:
      name: 租赁测试员
      mail:
        templateCode: CMAILTEMP170801000004
        email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com,christina.cheng@superbrandmall.com
      sms:
        templateCode: CMAILTEMP170801000005
        mobile: 13817200846,13818768168
    event:
      name: 场地测试员
      mail:
        templateCode: CMAILTEMP170801000004
        email: junkai.zhang@superbrandmall.com,jun.ma@superbrandmall.com,christina.cheng@superbrandmall.com
      sms:
        templateCode: CMAILTEMP170801000005
        mobile: 13817200846,13818768168

  customer:
    sms:
      templateCode: CMAILTEMP170801000003