spring:
  application:
    name: onlineleasing-customer
  profiles:
    include: common, data, redis, tianyancha
    active: dev, db_ol_dev, redis_dev, eureka_dev

server:
  port: 8990
  context-path:



