spring:
  datasource:
    #url: jdbc:mysql://10.130.12.15:3306/online_leasing_db_dev?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://10.130.12.15:3306/online_leasing_db_bk?characterEncoding=utf8&useSSL=false
    username: oldev%oldev
    password: p@ssw0rd
  redis:
    host: 10.130.12.15
    password: Sbm123

eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/

sync:
  cron:
    base:
      coords: 0 10 0 * * ?
      info:
        floor: 0 10 0 * * ?
        mall: 0 10 0 * * ?
      modality: 0 10 0 * * ?
