spring:
  application:
    name: onlineleasing-init
  profiles:
    include: common, data, redis
    active: test

server:
  port: 9000
  context-path:

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

init:
  shop:
    vr:
      path: upload/vr/{0}/{1}/tour.html