spring:
  datasource:
    url: jdbc:oracle:thin:@10.130.12.23:1521:HDAPP
    username: zdol
    password: zdol

eureka:
  instance:
    #实例ip
    ip-address: 10.130.12.15
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/

hd:
  url: http://10.130.12.22:7280/cre-agency-server