spring:
  datasource:
    url: jdbc:oracle:thin:@10.130.12.23:1521:HDAPP
    username: zdol
    password: zdol

eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
