spring:
  http:
    multipart:
      location: /home/microservice/tmp/  # 上传的临时目录

eureka:
  instance:
    #实例ip 配置在sh中
    ip-address: #10.130.12.43

hd:
  media:
    url: http://uat-olmedia.superbrandmall.com/HDMediaService-Web
