server:
  port: 8770
logging:
  file: /home/mircoservice/log/template.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: template

