spring:
  datasource:
    url: jdbc:mysql://10.130.12.15:3306/micro_service
    username: micro_user
    password: microService2018

eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://10.130.12.15:8761/eureka/
