spring:
  application:
    name: common-authorization
  profiles:
    include: common, data, redis
    active: dev, eureka_uat, db_ms_dev, redis_dev

server:
  port: 8730
  context-path:

jwt:
  tokenVersion: 1 #版本
  issuer: superbrandmall #发行人
  subject: Authorization #抽象主题
  hs256key: OL_SBM_p@ssw0rd #HS256 私钥
  ttl: 43200 # 12 * 60 * 60 秒; 12小时

verificationCode:
  default:
    sources: 23456789ABCDEFGHJKLMNPQRSTUVWXYZ #字体只显示大写，去掉了1,0,i,o几个容易混淆的字符
    size: 6